version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
      FLASK_ENV: production
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: my_train_titanic
    depends_on:
      - mysql
    networks:
      - backend

  nginx:
    image: nginx:alpine
    # build:
    #   context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    networks:
      - backend
    volumes:
      - ./nginx/certs:/etc/nginx/certs
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf

volumes:
  db_data:

networks:
  backend:
    driver: bridge
