version: "3.8"

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - backend

  flask:
    build: .
    container_name: flask
    restart: always
    environment:
      FLASK_ENV: development # 用來判斷切換開發還是生產模式
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: my_train_titanic
    depends_on:
      - mysql
    volumes:
      - D:/iSpan_docker_homework:/app
    networks:
      - backend
    ports:
      - "5000:5000"

volumes:
  db_data:

networks:
  backend:
    driver: bridge
